language: python
dist: bionic
python:
- '3.6'
node_js:
- '8'
cache:
  pip: true
  npm: true
install:
- npm install
- npm run build
- pip install -r requirements/dev.txt
- pip install coveralls
script:
- python manage.py collectstatic > /dev/null
- py.test --cov
- python manage.py makemigrations --dry-run --check --noinput
- "./node_modules/.bin/polylint -F"
- rm -rf static/
after_success:
- coveralls
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: loSDNJr/1BV5LdX2SDUvaNet3xbKNiW+PsazcSr38PylZQ/RLyDAcKzF8mxDW9LIiRpJTD0Dc8OwQlwWQWQhyUERM75gid/Sf5DxN8hfpwDNdpPvOsIrktZekir0CFhI1ezaHRWokZk3SmU8rzo6eG+uR6F1hKKP2zYDOWPKfrs/jHllbBB4p+P25IfxvdgX9t+t6aBACqUNzax9WIhmDyPPujWsDPyXOEfJcsgrGtmiCwZAAjSR+iMshWkQLh0kSmTQA/HwpuIx+T2zpWVEVu/rtxJ0FpWKQS7v2rah6wPJByNrkawGbjyhBKoKUj26Vz0Xr8SpNCu/EjAlxdQyy+GkRApGuW1+EXHwjRDjYWusfodbp/dEEnwXLugoSmRCDX8xhlc9llIGfMHKujz1dLKHoAKA6WgByVgFi0Ng0exlWZBJbX8QgbubdLXdqASj5NW3wpt7crTpz1gI7siVNPoNoa+VH+5hLMAtmX4RMDRyb5+4TnDbAf9iQYkHX+Z8D0Bxo81l4MycSuvBhK1uiO9t2dc+xZWI7rAkZdKllxDUCJAbM1kaUu9/Q7PJfQ2SJCE9DD7LaibV7iQPSmFrmrzXZax7R1QfYsb2Fd/ZzCeic/Kam87D/TdBqZ6MkZfjA/YZQD/NgEWvxo+vUm5zWUqlDAlcIpkPCREn4WjRRpc=
