language: python
dist: bionic
python:
- '3.6'
node_js:
- '8'
cache:
  pip: true
  npm: true
services:
- postgresql
addons:
  postgresql: '10'
install:
- npm install
- npm run build
- pip install -r requirements/dev.txt
- pip install coveralls
before_script:
- psql -c 'create database django;' -U postgres
- psql -c 'create database django_test;' -U postgres
script:
- python manage.py collectstatic > /dev/null
- py.test --cov
- python manage.py makemigrations --dry-run --check --noinput
- isort --diff -c adhocracy-plus apps tests
- flake8 adhocracy-plus apps tests --exclude migrations,settings
- npm run lint
- rm -rf static/
after_success:
- coveralls
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: "H+psJBcxW9xht3NZFQV6zfpse7j/A3L3l1APIqesXoHShyJ0cpHIMppb2nfpo2GWGzjEHuuKqAjW9dK4q0DKRAukoDwax6kLKcdWDtth6+HAzYj5B9mMjrkzFOo2QkVFLzYXTi+bgBepvFnTdJd8w3xPEAqZhVkaxjAFQLNKI1bFNQl8sDx1y8Mze3LrGjcobNMITbLgaIxfSmLxgLkQJVEZZU8rl4pE2QYPfC/ACubYVP6zEHfBo7CvQufDOa9XcLoTpMH5NRyRk3qmcWUDTwFi+63dP2/cgOHFO0Wq+WFHcQzvu2cRGmdyIOkYKGMCHUId4R+bKmJPDbLahPK38uBq4aLJRBwZAU68WKYpQwYbdolZfCW87tQ0MabmD0GBUPlwdpFtvmDiChAVFSDSyNMB0FQMk7fMlDSTiNjdP5ScT1y2a2jdnBwbSR0Q1uZC1QHf7b0rCfqBEVmmqIP3sY3lZu1xoR6EwJPOC/UdR9MGDuzymn/bPEiWh0ayQCxOlZxmnI05RQZfOA5sFEUXnb1i8aIR/ntW1uEXxbIf/4TgszLeJUvAAP4O75DhZqYRCEyV6zth7duZTr/0NoAOfcHtCq67LD00DYAys6zokaeom7yRaO3dgwwIa6hVy+GnsKlk/c7N6398TWj9a4BSPgwimWY+TrdNU2Vi3qjHZaE="
  - DJANGO_SETTINGS_MODULE='adhocracy-plus.config.settings.travis'
