language: python
dist: bionic
python:
- '3.6'
node_js:
- '8'
cache:
  pip: true
  npm: true
services:
- postgresql
addons:
  postgresql: '10'
install:
- npm install
- npm run build
- pip install -r requirements/dev.txt
- pip install coveralls
before_script:
- psql -c 'create database django;' -U postgres
- psql -c 'create database django_test;' -U postgres
script:
- python manage.py collectstatic > /dev/null
- py.test --cov
- python manage.py makemigrations --dry-run --check --noinput
- isort --diff -c adhocracy-plus apps tests
- flake8 adhocracy-plus apps tests --exclude migrations,settings
- npm run lint
- rm -rf static/
after_success:
- coveralls
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: "m7JUqJ+FwoF7Ou1pQNAJqpzf9A1HHIeqrAGZPxPyB4PxqnhqGAkrGdn/Kn/TJZbflKXuXrwt3eUecaUB1/T8y88jaeMqnHkyJOwNwgvfoT/rjJ9Uwwf+M2e4HHQ3wXCZYIxHzw3aEX3/4SdIH29n+jG6ew8VFBcLyE8P2BfA4uUn1ZP9q/xj5h61yNzyl1stctAj/Ib+tAJrNbB8ONq96yWMq6WA+9eN9RYP1nSRvuNkHAJMISx1DbLBZKk2naISP/EeVZWefmLuoJa5bLL6N8S5Qx0dEkJOOnHxljE0nVxXGY0Fz5PgJrakiJ/so68vBuJ5fSFcSmLry4eu/7ZDcNpUx7GkXsSd2wAweu9z7VbE38QanQorbYTNMK+T/tnMHq4BjD+6Ua664ToZp7mCqmz7Lv6a+RbWXWvCt36RIL4EsaGD+exOIXN+zeU8od3Wb9jtx0kkvZFb8WNUZZAPe74VeN0s0kARb7hgusFLkqrcbOoYm0QkSd7iYvd2b6tFB/E1rg92LBFJsAL6wuD7XoGnww5TCv3tQaT3O7HWSEHDQhJ7tL9Ng59gUbJE0qkZgooJEbha2oJX60KyrX7q3k379lIRXFYqxKcJd1JJUWH+4Fz5TvkOTa8KHVMvscdsvcjy8bR32BTxU5kmN9tMP6QnPkWm/276DlJk9EsWjiQ="
  - DJANGO_SETTINGS_MODULE='adhocracy-plus.config.settings.travis'
