# Generated by Django 3.2.12 on 2022-04-04 13:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a4comments', '0009_comment_is_blocked'),
        ('a4_candy_moderatorfeedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorCommentStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('statement', ckeditor.fields.RichTextField(blank=True, verbose_name='Moderator feedback')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a4comments.comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
