# Generated by Django 3.2.13 on 2022-04-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a4comments', '0009_comment_is_blocked'),
        ('a4_candy_moderatorfeedback', '0002_moderatorcommentstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorcommentstatement',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_statement', to='a4comments.comment'),
        ),
    ]
