# Generated by Django 3.2.18 on 2023-03-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_moderatorfeedback", "0003_alter_moderatorcommentstatement_comment"),
        (
            "a4_candy_moderatorfeedback",
            "0003_rename_statement_moderatorfeedback_feedback_text",
        ),
    ]

    operations = []
