# Generated by Django 3.2.18 on 2023-03-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_moderatorfeedback", "0004_merge_20230301_1649"),
        ("a4_candy_moderatorfeedback", "0004_verbose_name_created_modified"),
    ]

    operations = []
