# Generated by Django 3.2.14 on 2022-08-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('a4_candy_cms_settings', '0006_add_helptexts_to_organisation_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='platform_information',
            field=models.ForeignKey(blank=True, help_text='If set, a link to this page will added to the userdashboard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_information', to='wagtailcore.page'),
        ),
    ]
