# Generated by Django 3.2.14 on 2022-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_settings', '0007_importantpages_platform_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsettings',
            name='sample_project_slug',
            field=models.SlugField(blank=True, help_text='Slug of the sample project of this platform. Every new user will automatically follow this project.', max_length=255),
        ),
    ]
